### ISSUE TITLE
[Bug]: 開発者向けオプションが開かない

### ISSUE THREAD

**Issue by misssy-ms** [Kobold831/CPadCustomizeTool#10]
### 内容の詳細

チャレンジタッチNEOで､ 開発者向けオプションを開く を実行しても､パスワードを要求されて開けません｡

**Comment by awayume** [comment]
「学習用UI」になっているか確認してください。

**Comment by FullWidth-mion** [comment]
場所が間違っていると思われます。SetupLoginのIssueの方に移動してはどうでしょう

**Comment by awayume** [comment]
@missssssssssi-ms 
2024/11/28 18:00 JSTまでに返答がないのであればクローズします。
