### ISSUE TITLE
[Bug]: アプリがインストール(更新)できない

### ISSUE THREAD

**Issue by railroadcrossing** [Kobold831/CPadCustomizeTool#11]
### 内容の詳細

デバイスオーナーの機能を使ってapkファイル、xapkファイルともにサイレントインストールしようとしても、「エラーが発生しました。不明なエラーです」と出てインストールに失敗してしまいます。デバイスオーナーはDhizukuです。Dhizukuや、当アプリのアプリ権限は付与されています。さらに設定の「キャッシュをクリア」を選択すると、「消去できませんでした」と帰ってきます。

### 解決する方法

ランタイム権限を付けたりアインストールブロッカーをoffにしたりして試していますが2024年12月20日現在解決できていないため解決する方法はありません

**Comment by Kobold831** [comment]
原因解決にあたり以下情報を提供してほしいです。
1.インストールしようとしているapkまたは、 xapk、apkmファイル。

2.ファイル選択に内蔵（Android純正）ファイルブラウザを使用しているか。（サイレンインストールを押した時にファイルアプリの選択画面がでずにファイル選択画面がでれば純正ファイルブラウザです。）Solidエクスプローラー、ESエクスプローラーなどサードパーティのファイルブラウザでは使用できません。

**Comment by railroadcrossing** [comment]
インストールしようとしているアプリは以下のファイルです。
![image](https://github.com/user-attachments/assets/c7e9d591-2d88-4508-adf7-3f3fe82de26c)

![ss002 - TAB-A05-BD](https://github.com/user-attachments/assets/b7495da6-7500-4e03-8af4-19938c78f2ca)
ファイル選択は、左側のアプリを使用しています(ファイルマネージャーは使ってないです

追記：アカウントが登録されていたので削除してみましたが結果は変わらず
最終手段として初期化すればたぶん治ると思います

**Comment by Kobold831** [comment]
わかりました。以下を確認してほしいです。
1.画面の動画は提供できますか？
サイレントインストールをおしてファイル選択からエラー発生までお願いします。
2.メイン画面1番下のアプリの取得を押して表示される任意のアプリを押して正常にインストールできるかの確認。（行う前に、右上の︙を押してアプリ設定->インストールモードがdhizukuになっているかを確認してください。）

**Comment by railroadcrossing** [comment]
https://github.com/user-attachments/assets/9bfa6073-e9ff-4883-a9d0-c747e755c987


https://github.com/user-attachments/assets/bc49d990-c1d9-4120-95f5-218a3db847a8

過去にはちゃんとインストールやアプリの更新はできていました。自分なんかやっちゃったっけ...(´・ω・｀)

**Comment by Kobold831** [comment]
いま手元に端末がないので、明日の夜に対応します！

**Comment by Kobold831** [comment]
こちらで複数のファイルを試してみましたが、すべて正常に動作しました。
そのため、報告された事象を確認することができませんでした。

https://drive.google.com/file/d/1PAT90yyV1NH_bt_PnXi73fOEpy7kVgYJ/view?usp=sharing

https://drive.google.com/file/d/1Pvy4TVQUpUiq_flF7HN3jHa4_NmHtzVa/view?usp=sharing

https://drive.google.com/file/d/1RNXnlVBIfu2-gwlYpMOFAj5RPPcTuuB0/view?usp=sharing

https://drive.google.com/file/d/1hotsSp-s--OfURbuG8KHm6CnySz58qq5/view?usp=sharing

一度アプリの再インストールを試してみてください。
また、下記URLよりDhizukuの更新を試してみてください。

https://github.com/iamr0s/Dhizuku/releases/download/v2.9/Dhizuku_v2.9.apk

試してみても問題が改善しないようであれば教えて下さい。
その際に、インストールを試みようとしているapkファイルをこちらに何かしらの方法で共有してほしいです。

**Comment by Kobold831** [comment]
いま気づいたんですが、以下の方法を試してもらえますか？
１．サイレントインストールを押してファイル選択画面を表示してください。
２．左上の≡アイコンを押してください。
３．次から開く：が表示されたらデバイス名かSDカードの欄をタップしてください。
４．目的のファイルを押してください。（動画を見る限りおそらくダウンロードフォルダにあると思います。）

**Comment by Kobold831** [comment]
現象を再現できました！
Dhizukuを最新バージョンにして試してみたところ同現象を再現できました。
原因はアプリが新しいバージョンのDhizukuに対応していないためだと思われます。
最新バージョンのDhizukuに対応するようにしますが、時間がかかるのでv2.8のDhizukuを使用してください。

https://github.com/iamr0s/Dhizuku/releases/download/v2.8/Dhizuku_v2.8.apk

**Comment by railroadcrossing** [comment]
一部のアプリはインストールに成功しました。
一部のアプリはインストールに失敗しました。
![image](https://github.com/user-attachments/assets/8d199999-3915-45ee-a903-f38650d0ced4)
こんな感じでなんかファイルにアクセスできないようです
ちゃんとファイルかここから選択してるんだけどなぁ...
![image](https://github.com/user-attachments/assets/53bfcb97-4453-44d9-9b83-240718d488da)

**Comment by Kobold831** [comment]
>一部のアプリはインストールに失敗しました。

そのapkファイルの提供は可能ですか？

**Comment by railroadcrossing** [comment]
すいません、カスタマイズツールを更新したら一つを除いてアプリの成功しました。
ただその一つは過去にadb経由でインストールしていたのでそれが原因かもしれないです...
https://d.kuku.lu/hv4zwxahj

**Comment by Kobold831** [comment]
わかりました！
