### ISSUE TITLE
[Bug]: 新機能のバグ（？）

### ISSUE THREAD

**Issue by ghost** [Kobold831/CPadCustomizeTool#12]
### 内容の詳細

**【環境】**
パッドチャレンジ NEXT （学習環境、通常環境併用）
Android 9、ビルド 01.03.000 release-keys（2024/12/25 時点で最新のバージョン）

**【詳細】**
報告の対象バージョン：2.4.3
▶オフライン時に空白が表示される。
・仕様かどうかはわかりませんが、空白が表示されます。タップすると「アプリのお知らせ」の題字のみが表示されます。
![IMG_20241225_163331_256](https://github.com/user-attachments/assets/aafdd3d4-c3e8-4525-a47a-6ab19b0abf0c)

▶アプリ内の「アプリのお知らせ」にて
　・オフラインだとアプリのお知らせが正常に機能していない。（仕様？）
![Screenshot_20241225-163524](https://github.com/user-attachments/assets/e70e41c2-cd69-4ffa-be94-59b0ed90ee09)

 以上です。

### 解決する方法

詳しいコードなどのことはわかりません。すみません。

**Comment by Kobold831** [comment]
データを取得して表示しているので、仕様になります。
オフライン時は表示しないようにします。

**Comment by ghost** [comment]
分かりました。ありがとうございます。
