### ISSUE TITLE
緊急モードの実行時にバグが発生する

### ISSUE THREAD

**Issue by Awayume** [Kobold831/CPadCustomizeTool#2]
1. ｢選択した講座は······｣と一瞬表示される
2. ホームランチャー選択画面が表示される

**Comment by Kobold831** [comment]
正しく修正できているか確認してください。

**Comment by Awayume** [comment]
確認したところ、どちらの講座を選択しても｢選択した講座は······｣と表示されます。

**Comment by Awayume** [comment]
解決済み
