### ISSUE TITLE
`○○を維持`という設定をオフにするとアプリがクラッシュする

### ISSUE THREAD

**Issue by Awayume** [Kobold831/CPadCustomizeTool#4]
現在確認できているもの
- システムUIを通常用に維持
- ナビゲーションバーの表示を維持
- 提供元不明のアプリの許可を維持
- USBデバッグの有効を維持
- ホームを維持

クラッシュログ
![_20220331_154535](https://user-images.githubusercontent.com/79361022/160993103-635b12e8-41a0-41db-8f3f-8bdfda81d547.JPG)

確認できた端末
- チャレンジパッド2

**Comment by Kobold831** [comment]
わかりました。ただしチャレンジパッドneoでデバッグしていますがその事象はビルドしたときに確認できなかったので修正に時間がかかります。

**Comment by Kobold831** [comment]
おそらく修正できました。
