### ISSUE TITLE
`デバイスオーナーの機能`が開けない

### ISSUE THREAD

**Issue by Awayume** [Kobold831/CPadCustomizeTool#5]
クラッシュログ
![_20220331_154754](https://user-images.githubusercontent.com/79361022/160993423-468b685a-e043-46b5-b22c-2e29d1972167.JPG)

確認できた端末
- チャレンジパッド2

**Comment by Kobold831** [comment]
ランタイムパーミッションの許可の強制はチャレンジパッド2で動作しているAndroid5.1では対応していません。したがってチャレンジパッド2では変更できないようにコードの修正を行います。

**Comment by Kobold831** [comment]
修正しました。
