### ISSUE TITLE
ツールからホームランチャーを変更できない

### ISSUE THREAD

**Issue by awayume** [Kobold831/CPadCustomizeTool#7]
#### 条件
- ホームランチャー維持機能が有効

#### 再現手順
1. ホームランチャー維持機能を無効化
2. ツールからホームランチャーを変更

#### 状況
2.と同時にホームランチャー維持機能が勝手に有効化され、維持機能無効化前のホームランチャーに戻る

#### 環境
チャレンジパッド2 (02.04.000)

### 解決する方法

1.の後ツールを閉じ、設定アプリからホームランチャーを変更する

**Comment by Kobold831** [comment]
報告ありがとうございます。
検証を行い修正に取り組みますが、時間がかかってしまうので、しばらくお待ちください。

**Comment by Kobold831** [comment]
先ほど修正を反映しました。
正常に値が保存できていなかったため、正常に保存できるように修正しました。
