### ISSUE TITLE
[Bug]:「通常モード」、「緊急モード」が正常に動作しない。

### ISSUE THREAD

**Issue by ghost** [Kobold831/CPadCustomizeTool#8]
### _**【環境】**_
チャレンジパッド NEXT （学習環境、通常環境併用）
Android 9、ビルド 01.03.000 release-keys（2024/07/09時点で最新のバージョン）

### _**【詳細】**_
報告の対象バージョン：_2.3.1_
**▶緊急モード、通常モードの両方にて**
　・実行をタップし、「実行しました」と表示されるものの、UIやナビゲーションバー、ホームアプリなど実行時に変更されるはずの設定が変更されない。
　・本アプリから直接実行、ショートカットから実行など様々な方法で実行しても、正常動作しない。
　・キャッシュクリア、ユーザーデータのクリア、タブレットの初期化、再インストールなどを試しても改善されない。
　・エラーログは無し。
　・変更内容をどのような条件にしても、実行できない。
　・権限はすべて付与済み。（デバイスオーナーのみ未付与）
**▶アプリ内の「USBデバック」にて**
　・USBデバックに関連する３項目すべてにて、この項目のトグルスイッチをタップすると、「権限を付与してから再試行してください」と表示される。（ちなみにデバイスオーナー以外の権限は付与済みです。）
　・エラーログなし。

以上です。

### 解決する方法

根本的な解決方法は分かりません。すみません。
現在は、上記が正常動作する、旧バージョンの2.3.0を使用しています。

**Comment by Kobold831** [comment]
報告ありがとうございます。
v2.3.1にて設定保存に関する修正行ったことで、発生した不具合と思われます。
原因を特定して修正するため、しばらくお待ちください。

**Comment by Kobold831** [comment]
先ほど修正を反映してv2.3.2をリリースしました。
ご確認ください。

**Comment by ghost** [comment]
ありがとうございます
