### ISSUE TITLE
[Bug]: 学習システムUIに正常に変更されない。

### ISSUE THREAD

**Issue by ghost** [Kobold831/CPadCustomizeTool#9]
###  _**【環境】**_

チャレンジパッド NEXT （学習環境、通常環境併用）
Android 9、ビルド 01.03.000 release-keys（2024/07/25時点で最新のバージョン）

### **_【詳細】_**
報告の対象バージョン：2.3.4 , 2.3.5
▶緊急モードにて
　・緊急モードの起動をタップし、「実行しました」と表示され、ナビゲーションバー、ホームアプリなどは変更されるが、学習用システムUIに正常に変更されない（通常UI、学習UIが交互に変更される？）（緊急モード起動で学習UI起動→ホームボタンで中ゼミホームローディング→通常UI（0.05秒間）→学習UI（0.05秒間）→通常UI（継続））。
　・本アプリから直接実行、ショートカットから実行など様々な方法で実行しても、正常動作しない。
　・キャッシュクリア、ユーザーデータのクリアを試しても改善されない。
　・エラーログは無し。
　・権限はすべて付与済み。（デバイスオーナーのみ未付与）

### 解決する方法

不明です。すみません。

**Comment by ghost** [comment]
何故か正常に動作するようになりました。

**Comment by ghost** [comment]
再発しました。

**Comment by Kobold831** [comment]
わかりました。

**Comment by ghost** [comment]
すみません、タブレット本体を初期化したら治りました。ご対応ありがとうございました。
